apiVersion: v1
kind: Service
metadata:
  name: location-discovery
  namespace: vibe-social
  labels:
    app: location-discovery
spec:
  type: ClusterIP
  selector:
    app: location-discovery
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
