apiVersion: v1
kind: Service
metadata:
  name: event-tracking-grpc
  namespace: vibe-social
  labels:
    app: event-tracking
spec:
  type: LoadBalancer
  selector:
    app: event-tracking
  ports:
    - protocol: TCP
      name: grpc
      port: 81
      targetPort: 8081
